definitions:
  dto.ApiResponse:
    properties:
      data: {}
      error:
        type: string
      message:
        type: string
      status:
        type: string
      status_code:
        type: integer
    type: object
  dto.CreatePaymentRequest:
    properties:
      currency_code:
        type: string
      email:
        type: string
      plan_id:
        type: string
    required:
    - currency_code
    type: object
info:
  contact: {}
paths:
  /api/v1/currencies:
    get:
      description: Returns a list of all available currencies
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ApiResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ApiResponse'
      summary: Get all available currencies
      tags:
      - currencies
  /api/v1/payments/create:
    post:
      description: Creates a payment in the database and returns payment details
      parameters:
      - description: Payment Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreatePaymentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ApiResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ApiResponse'
      summary: Create a payment
      tags:
      - create
  /api/v1/plans:
    get:
      description: Returns a list of all subscription plans
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ApiResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ApiResponse'
      summary: Get all plans
      tags:
      - plans
swagger: "2.0"
